//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Way.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DescricaoTabelasPadroes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DescricaoTabelasPadroes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Way.Domain.Resources.DescricaoTabelasPadroes", typeof(DescricaoTabelasPadroes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aluno.
        /// </summary>
        public static string CaracterizacaoAluno {
            get {
                return ResourceManager.GetString("CaracterizacaoAluno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa.
        /// </summary>
        public static string CaracterizacaoEmpresa {
            get {
                return ResourceManager.GetString("CaracterizacaoEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pessoa física.
        /// </summary>
        public static string CaracterizacaoFisica {
            get {
                return ResourceManager.GetString("CaracterizacaoFisica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pessoa jurídica.
        /// </summary>
        public static string CaracterizacaoJuridica {
            get {
                return ResourceManager.GetString("CaracterizacaoJuridica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motorista.
        /// </summary>
        public static string CaracterizacaoMotorista {
            get {
                return ResourceManager.GetString("CaracterizacaoMotorista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsável.
        /// </summary>
        public static string CaracterizacaoResponsavel {
            get {
                return ResourceManager.GetString("CaracterizacaoResponsavel", resourceCulture);
            }
        }
    }
}
