//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Way.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MensagensEntidades {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MensagensEntidades() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Way.Domain.Resources.MensagensEntidades", typeof(MensagensEntidades).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ano de fabricação do veículo está inválido.
        /// </summary>
        public static string AnoFabricacaoVeiculoInvalido {
            get {
                return ResourceManager.GetString("AnoFabricacaoVeiculoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deve estar entre  o intervalo -90 e 90.
        /// </summary>
        public static string Coordenada_Intervalo {
            get {
                return ResourceManager.GetString("Coordenada_Intervalo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data {0} deve ser informada.
        /// </summary>
        public static string DataDeveSerInformada {
            get {
                return ResourceManager.GetString("DataDeveSerInformada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de vencimento.
        /// </summary>
        public static string DataVencimento {
            get {
                return ResourceManager.GetString("DataVencimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail não é válido.
        /// </summary>
        public static string EmailInvalido {
            get {
                return ResourceManager.GetString("EmailInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um erro ocorreu ao executar a operação {0}.
        /// </summary>
        public static string ErroAoRealizarOperacao {
            get {
                return ResourceManager.GetString("ErroAoRealizarOperacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um erro inesperado acaba de acontecer, reporte o erro descrevendo qual operação esta realizando.
        /// </summary>
        public static string ErroInesperado {
            get {
                return ResourceManager.GetString("ErroInesperado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuário ou senha informados estão incorretos.
        /// </summary>
        public static string LoginIncorreto {
            get {
                return ResourceManager.GetString("LoginIncorreto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome de login é obrigatório.
        /// </summary>
        public static string LoginObrigatorio {
            get {
                return ResourceManager.GetString("LoginObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A marca do veículo é obrigartória.
        /// </summary>
        public static string MarcaVeicuiloObrigatorio {
            get {
                return ResourceManager.GetString("MarcaVeicuiloObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O modelo do veículo é obrigatório.
        /// </summary>
        public static string ModeloVeiculoObrigatorio {
            get {
                return ResourceManager.GetString("ModeloVeiculoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número de parcelas deve ser maior que zero.
        /// </summary>
        public static string ParcelasCarnePositivas {
            get {
                return ResourceManager.GetString("ParcelasCarnePositivas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uma pessoa não pode ser cadastrada sem ao menos um documento.
        /// </summary>
        public static string PessoaPrecisaDeAoMenosUmDocumento {
            get {
                return ResourceManager.GetString("PessoaPrecisaDeAoMenosUmDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve existir uma pessoa responsável pelo carne.
        /// </summary>
        public static string PessoaResponsavelCarne {
            get {
                return ResourceManager.GetString("PessoaResponsavelCarne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A plca do veículo é obrigatória.
        /// </summary>
        public static string PlacaVeiculoObrigatoria {
            get {
                return ResourceManager.GetString("PlacaVeiculoObrigatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A confirmação da senha difere da senha informada.
        /// </summary>
        public static string SenhaDivergente {
            get {
                return ResourceManager.GetString("SenhaDivergente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve não pode estar em branco.
        /// </summary>
        public static string SenhaObrigatoria {
            get {
                return ResourceManager.GetString("SenhaObrigatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve ter pelo menos seis (6) caracteres.
        /// </summary>
        public static string TamanhoSenhaIncorreto {
            get {
                return ResourceManager.GetString("TamanhoSenhaIncorreto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário salvo com sucesso!.
        /// </summary>
        public static string UsuarioSalvo {
            get {
                return ResourceManager.GetString("UsuarioSalvo", resourceCulture);
            }
        }
    }
}
